services:
  - type: web
    name: fightcrewapp-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: starter
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: ADMIN_EMAILS
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: PORT
        value: "10000"
      - key: SKIP_EMAIL_VERIFICATION
        sync: false
