import React from 'react';
import {
  AbsoluteFill,
  Sequence,
  interpolate,
  useCurrentFrame,
  Easing,
  Img,
  staticFile,
} from 'remotion';
import { COLORS, SHEAR, SAFE, TIMING, VIDEO } from './brand';
import { NumberPop } from './components/NumberPop';
import { StarRow } from './components/StarRow';
import { Watermark } from './components/Watermark';
import { FightCard } from './components/FightCard';
import { FightBackground, AmbientGlow } from './components/Background';
import { Grain } from './components/Grain';
import { matchupLabel, type VideoPayload, type VideoFight } from './data/types';
// fightId -> "backgrounds/<file>", generated by scripts/syncBackgrounds.mjs before every
// render (chained in package.json + the panel server). Compositions can't list public/
// at render time, so presence must be baked in at bundle time.
import backgroundManifest from './data/backgrounds.json';

const BACKGROUNDS = backgroundManifest as Record<string, string>;
const backgroundFor = (f: VideoFight): string | null => BACKGROUNDS[f.fightId] ?? null;

/** ④ Whoosh slide — the ONE transition, used everywhere (spec §9.4). */
const WhooshSlide: React.FC<{ children: React.ReactNode; durationInFrames: number }> = ({
  children,
  durationInFrames,
}) => {
  const frame = useCurrentFrame();
  const t = TIMING.transition;

  const enterX = interpolate(frame, [0, t], [VIDEO.width, 0], {
    extrapolateLeft: 'clamp',
    extrapolateRight: 'clamp',
    easing: Easing.bezier(0.33, 1, 0.68, 1),
  });
  const exitX = interpolate(frame, [durationInFrames - t, durationInFrames], [0, -VIDEO.width], {
    extrapolateLeft: 'clamp',
    extrapolateRight: 'clamp',
    easing: Easing.bezier(0.33, 1, 0.68, 1),
  });
  const opacity = interpolate(
    frame,
    [0, t, durationInFrames - t, durationInFrames],
    [0, 1, 1, 0],
    { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' },
  );
  // Impact settle: the card arrives a touch oversized and lands over ~6 frames.
  // Reads as weight at the end of the slide instead of a flat stop.
  const settle = interpolate(frame, [t - 2, t + 6], [1.03, 1], {
    extrapolateLeft: 'clamp',
    extrapolateRight: 'clamp',
    easing: Easing.bezier(0.33, 1, 0.68, 1),
  });

  return (
    <AbsoluteFill style={{ transform: `translateX(${enterX + exitX}px) scale(${settle})`, opacity }}>
      {children}
    </AbsoluteFill>
  );
};

/**
 * ② Blur Reveal — hook cold-open, blur held high. The retention engine.
 *
 * `ratedCount` must be a real, defensible figure. "Fans rated EVERY UFC fight" was the
 * first draft and it is false: 7,054 of 8,945 UFC fights in the DB carry a rating. No
 * superlative outruns the table — that rule applies to video copy, not just articles.
 */
/**
 * Headlines are generated per format, so their length varies a lot
 * ("7,054 UFC FIGHTS." vs "16 CONOR MCGREGOR FIGHTS."). Shrink to fit the safe column
 * rather than letting a long fighter name run under the share rail.
 */
const fitHeadline = (headline: string, max = 82) => {
  const usable = VIDEO.width - SAFE.left - SAFE.right;
  const longest = Math.max(...headline.split('\n').map((l) => l.length));
  // Anton is condensed; ~0.46em average advance is a good empirical fit.
  return Math.min(max, Math.floor(usable / (0.46 * longest)));
};

const Hook: React.FC<{ topRating: number; headline: string; backgroundSrc: string | null }> = ({
  topRating,
  headline,
  backgroundSrc,
}) => {
  const frame = useCurrentFrame();
  const headlineOpacity = interpolate(frame, [0, 12], [0, 1], {
    extrapolateLeft: 'clamp',
    extrapolateRight: 'clamp',
  });
  const headlineY = interpolate(frame, [0, 16], [40, 0], {
    extrapolateLeft: 'clamp',
    extrapolateRight: 'clamp',
    easing: Easing.bezier(0.33, 1, 0.68, 1),
  });

  return (
    <AbsoluteFill>
      {/* The opening frame is the scroll-stopper — a photo matters most here. Heavily
          blurred: mood, not subject (and never the #1 fight's photo, see backgroundFor
          call site — the payoff must not leak). */}
      {backgroundSrc ? (
        <FightBackground src={backgroundSrc} durationInFrames={TIMING.hook} blur={30} opacity={0.2} />
      ) : (
        <AmbientGlow durationInFrames={TIMING.hook} />
      )}
      <AbsoluteFill
        style={{
          alignItems: 'center',
          justifyContent: 'center',
          paddingTop: SAFE.top,
          paddingBottom: SAFE.bottom,
          paddingLeft: SAFE.left,
          paddingRight: SAFE.right,
        }}
      >
        <div
        style={{
          opacity: headlineOpacity,
          transform: `translateY(${headlineY}px)`,
          fontFamily: 'Anton, sans-serif',
          fontSize: fitHeadline(headline),
          color: COLORS.white,
          textAlign: 'center',
          lineHeight: 1.1,
          marginBottom: 60,
        }}
      >
        {headline.split('\n').map((line, i) => (
          <React.Fragment key={i}>
            {i > 0 && <br />}
            {line}
          </React.Fragment>
        ))}
      </div>

      <div
        style={{
          fontFamily: 'Inter, sans-serif',
          fontSize: 34,
          color: COLORS.gray,
          marginBottom: 24,
          opacity: headlineOpacity,
        }}
      >
        One scored a
      </div>

        {/* the #1 number, held BLURRED — people stay to un-blur it.
            Blur must be heavy enough to be genuinely unreadable; at 26 the digits
            were still legible, which kills the whole retention device. */}
        <NumberPop value={topRating} startFrame={6} fontSize={300} blurAmount={44} />
      </AbsoluteFill>
    </AbsoluteFill>
  );
};

const Tease: React.FC<{ fights: VideoFight[] }> = ({ fights }) => {
  const frame = useCurrentFrame();
  const shots = fights.flatMap((f) => [f.fighter1, f.fighter2]).slice(0, 10);

  return (
    <AbsoluteFill>
      <AmbientGlow durationInFrames={TIMING.tease} />
      <AbsoluteFill
        style={{
          alignItems: 'center',
          justifyContent: 'center',
          paddingTop: SAFE.top,
          paddingBottom: SAFE.bottom,
          paddingLeft: SAFE.left,
          paddingRight: SAFE.right,
        }}
      >
      <div
        style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(2, 1fr)',
          gap: 20,
          marginBottom: 50,
        }}
      >
        {shots.map((s, i) => {
          const delay = i * 3;
          const local = frame - delay;
          const scale = interpolate(local, [0, 8], [0.9, 1], {
            extrapolateLeft: 'clamp',
            extrapolateRight: 'clamp',
            easing: Easing.bezier(0.33, 1, 0.68, 1),
          });
          const opacity = interpolate(local, [0, 8], [0, 1], {
            extrapolateLeft: 'clamp',
            extrapolateRight: 'clamp',
          });
          return (
            <div
              key={s.id + i}
              style={{
                width: 180,
                height: 180,
                borderRadius: 12,
                overflow: 'hidden',
                backgroundColor: COLORS.panel,
                transform: `scale(${scale})`,
                opacity,
              }}
            >
              {s.headshot ? (
                <Img
                  src={staticFile(s.headshot)}
                  style={{ width: '100%', height: '100%', objectFit: 'cover' }}
                />
              ) : null}
            </div>
          );
        })}
      </div>

      <div
        style={{
          fontFamily: 'Anton, sans-serif',
          fontSize: 66,
          color: COLORS.gold,
          transform: SHEAR,
          textAlign: 'center',
        }}
      >
        THE {fights.length} GREATEST
      </div>
        <div
          style={{
            fontFamily: 'Inter, sans-serif',
            fontSize: 32,
            color: COLORS.gray,
            marginTop: 14,
          }}
        >
          counting down
        </div>
      </AbsoluteFill>
    </AbsoluteFill>
  );
};

/** The #1 payoff — un-blur, biggest pop, let it sit. */
const Payoff: React.FC<{
  fight: VideoFight;
  caption: string;
  claim: string;
  backgroundSrc: string | null;
}> = ({ fight, caption, claim, backgroundSrc }) => {
  const frame = useCurrentFrame();

  // Hold a beat of near-empty frame, then ramp blur 26 -> 0 over ~0.4s.
  const blur = interpolate(frame, [30, 42], [44, 0], {
    extrapolateLeft: 'clamp',
    extrapolateRight: 'clamp',
    easing: Easing.bezier(0.33, 1, 0.68, 1),
  });

  const setupOpacity = interpolate(frame, [0, 14], [0, 1], {
    extrapolateLeft: 'clamp',
    extrapolateRight: 'clamp',
  });
  const captionOpacity = interpolate(frame, [60, 72], [0, 1], {
    extrapolateLeft: 'clamp',
    extrapolateRight: 'clamp',
  });

  return (
    <AbsoluteFill>
      {backgroundSrc ? (
        <FightBackground src={backgroundSrc} durationInFrames={TIMING.payoff} />
      ) : (
        <AmbientGlow durationInFrames={TIMING.payoff} />
      )}
      <AbsoluteFill
        style={{
          alignItems: 'center',
          justifyContent: 'center',
          paddingTop: SAFE.top,
          // Taller number block (star behind the score) than the old bar layout — reserve
          // more at the bottom so the caption stays clear of the platform UI.
          paddingBottom: 360,
          paddingLeft: SAFE.left,
          paddingRight: SAFE.right,
        }}
      >
      <div
        style={{
          opacity: setupOpacity,
          fontFamily: 'Anton, sans-serif',
          fontSize: 58,
          color: COLORS.gold,
          transform: SHEAR,
          marginBottom: 24,
        }}
      >
        #1
      </div>

      <div style={{ display: 'flex', gap: 24, opacity: setupOpacity, marginBottom: 28 }}>
        {[fight.fighter1, fight.fighter2].map((f) => (
          <div
            key={f.id}
            style={{
              width: 280,
              height: 280,
              borderRadius: 16,
              overflow: 'hidden',
              backgroundColor: COLORS.panel,
            }}
          >
            {f.headshot ? (
              <Img
                src={staticFile(f.headshot)}
                style={{
                  width: '100%',
                  height: '100%',
                  objectFit: 'cover',
                  // Same slow push-in as the countdown cards — see Headshot in FightCard.
                  transform: `scale(${interpolate(frame, [0, TIMING.payoff], [1, 1.07])})`,
                }}
              />
            ) : null}
          </div>
        ))}
      </div>

      <div
        style={{
          opacity: setupOpacity,
          fontFamily: 'Anton, sans-serif',
          fontSize: 80,
          color: COLORS.white,
          transform: SHEAR,
          textAlign: 'center',
          marginBottom: 12,
        }}
      >
        {matchupLabel(fight)}
      </div>

      {/* The #1 card was the only one not naming its event — the payoff is exactly where
          a viewer wants to know which card this was. */}
      <div
        style={{
          opacity: setupOpacity,
          fontFamily: 'Inter, sans-serif',
          fontSize: 30,
          color: COLORS.gray,
          textAlign: 'center',
          marginBottom: 18,
        }}
      >
        {fight.event} · {fight.eventDateLabel}
      </div>

      <NumberPop value={fight.rating} startFrame={30} fontSize={280} blurAmount={blur} />

      <div style={{ marginTop: 8 }}>
        <StarRow rating={fight.rating} startFrame={42} size={64} gap={12} />
      </div>
      <div
        style={{
          fontFamily: 'Inter, sans-serif',
          fontSize: 30,
          color: COLORS.gray,
          marginTop: 18,
        }}
      >
        {fight.votes} fans rated it · {claim}
      </div>

      <div
        style={{
          opacity: captionOpacity,
          fontFamily: 'Inter, sans-serif',
          fontWeight: 600,
          fontSize: 38,
          color: COLORS.white,
          textAlign: 'center',
          marginTop: 34,
          maxWidth: 820,
          lineHeight: 1.3,
        }}
      >
        {caption}
      </div>
      </AbsoluteFill>
    </AbsoluteFill>
  );
};

const CTA: React.FC = () => {
  const frame = useCurrentFrame();
  const scale = interpolate(frame, [0, 20], [0.7, 1], {
    extrapolateLeft: 'clamp',
    extrapolateRight: 'clamp',
    easing: Easing.bezier(0.33, 1, 0.68, 1),
  });
  const opacity = interpolate(frame, [0, 14], [0, 1], {
    extrapolateLeft: 'clamp',
    extrapolateRight: 'clamp',
  });
  const tagOpacity = interpolate(frame, [22, 36], [0, 1], {
    extrapolateLeft: 'clamp',
    extrapolateRight: 'clamp',
  });

  return (
    <AbsoluteFill
      style={{
        alignItems: 'center',
        justifyContent: 'center',
        paddingBottom: SAFE.bottom,
      }}
    >
      <Img
        src={staticFile('brand/lockup.png')}
        style={{ width: 620, transform: `scale(${scale})`, opacity }}
      />
      <div
        style={{
          opacity: tagOpacity,
          fontFamily: 'Anton, sans-serif',
          fontSize: 58,
          color: COLORS.gold,
          transform: SHEAR,
          marginTop: 40,
          textAlign: 'center',
        }}
      >
        {/* Slogan is used VERBATIM, including casing — it is a locked brand asset. */}
        Never miss a Good Fight.
      </div>
      <div
        style={{
          opacity: tagOpacity,
          fontFamily: 'Inter, sans-serif',
          fontSize: 32,
          color: COLORS.gray,
          marginTop: 22,
          textAlign: 'center',
        }}
      >
        Rate them yourself · goodfights.app
      </div>
    </AbsoluteFill>
  );
};

export const Countdown: React.FC<{
  payload: VideoPayload;
  captions: Record<string, string>;
}> = ({ payload, captions }) => {
  const fights = [...payload.fights].sort((a, b) => a.rank - b.rank);
  const top = fights[0];
  const countdownFights = fights.slice(1).reverse(); // #5, #4, #3, #2

  // Fallback carries the finish ONLY — the event and date are already on the card's meta
  // line, and printing the outcome in both places was the duplication on screen.
  const captionFor = (f: VideoFight) =>
    captions[f.fightId] ?? f.finishLabel ?? 'Went the distance';

  let cursor = 0;
  const hookStart = cursor;
  cursor += TIMING.hook;
  const teaseStart = cursor;
  cursor += TIMING.tease;
  const cardStarts = countdownFights.map((_, i) => teaseStart + TIMING.tease + i * TIMING.perCard);
  cursor = teaseStart + TIMING.tease + countdownFights.length * TIMING.perCard;
  const payoffStart = cursor;
  cursor += TIMING.payoff;
  const ctaStart = cursor;

  // The hook's backdrop comes from the LOWEST-ranked fight with a photo — never #1.
  // The whole video is a countdown to the payoff; its photo in the opening frame,
  // even blurred, is a leak. countdownFights already runs #5 -> #2.
  const hookBackground = countdownFights.map(backgroundFor).find(Boolean) ?? null;

  return (
    <AbsoluteFill style={{ backgroundColor: COLORS.bg }}>
      <Sequence from={hookStart} durationInFrames={TIMING.hook}>
        <Hook topRating={top.rating} headline={payload.hookHeadline} backgroundSrc={hookBackground} />
      </Sequence>

      <Sequence from={teaseStart} durationInFrames={TIMING.tease}>
        <Tease fights={fights} />
      </Sequence>

      {countdownFights.map((f, i) => (
        <Sequence key={f.fightId} from={cardStarts[i]} durationInFrames={TIMING.perCard}>
          <WhooshSlide durationInFrames={TIMING.perCard}>
            <FightCard
              fight={f}
              caption={captionFor(f)}
              total={fights.length}
              background={backgroundFor(f)}
            />
          </WhooshSlide>
        </Sequence>
      ))}

      <Sequence from={payoffStart} durationInFrames={TIMING.payoff}>
        {/* The superlative is scoped by the pull, never hardcoded — a Nate Diaz list's #1
            is his highest-rated fight, not the app's. Older payloads get a claim that is
            true of any list rather than one that might not be. */}
        <Payoff
          fight={top}
          caption={captionFor(top)}
          claim={payload.payoffLabel ?? 'the highest-rated fight on this list'}
          backgroundSrc={backgroundFor(top)}
        />
      </Sequence>

      <Sequence from={ctaStart} durationInFrames={TIMING.cta}>
        <CTA />
      </Sequence>

      {/* watermark on everything except the outro */}
      <Sequence from={0} durationInFrames={ctaStart}>
        <Watermark />
      </Sequence>

      {/* film grain over every scene — the flat-digital tell is the thing it kills */}
      <Grain />
    </AbsoluteFill>
  );
};

export const countdownDuration = (fightCount: number) =>
  TIMING.hook +
  TIMING.tease +
  (fightCount - 1) * TIMING.perCard +
  TIMING.payoff +
  TIMING.cta;
