/**
 * Editorial retrospective for each Best Fights year page — a few honest
 * sentences about what that year in combat sports was actually like, name-
 * checking fights that sit at the top of OUR fan ratings for the year (so the
 * copy always agrees with the list it sits above). Years without an entry get
 * a data-driven fallback line built in the page.
 *
 * Voice: fan-to-fan, no hype-slop, no em dashes (house style).
 */
export const BEST_FIGHT_YEAR_NOTES: Record<number, string> = {
  2007: 'This was the year the sport went properly mainstream: the post-TUF boom in full swing, Quinton Jackson knocking out Chuck Liddell for the belt, and Gabriel Gonzaga head-kicking Cro Cop into another dimension. The ratings pool from 2007 is small, but the fights that survive in fan memory earned their place.',
  2008: 'The Brock Lesnar era arrived in 2008, and Frank Mir handing him a submission loss in his UFC debut is still one of the great what-if moments. Anderson Silva was untouchable at middleweight, Quinton Jackson and Wanderlei Silva finished their blood feud, and sleeper brawls like Heath vs Boetsch remind you the undercards delivered too.',
  2009: 'The year of UFC 100. Dan Henderson iced Michael Bisping with the most replayed right hand of the decade, Anderson Silva did the untouchable-matrix routine on Forrest Griffin, and Diego Sanchez and Clay Guida had a war so wild it still tops fan ratings for the whole year.',
  2010: 'A vintage year for violence. Chris Leben and Yoshihiro Akiyama went to war two weeks after Leben had already fought, the Korean Zombie and Leonard Garcia swung until nobody could breathe, Shogun took Machida\'s 0, and Anderson Silva pulled off the triangle against Chael Sonnen with two minutes left in a fight he was losing 4 rounds to none.',
  2011: 'Henderson vs Shogun at UFC 139 is on the shortlist for greatest fight of all time, and fans here rate it the best of the year. Add Chandler vs Alvarez, one of the best title fights Bellator ever produced, plus Edgar vs Maynard III, and Kongo\'s dead-man-walking comeback KO of Pat Barry, and 2011 holds up against any year in the sport\'s history.',
  2012: 'The Korean Zombie and Dustin Poirier put on a grappling-and-gore classic that fans still rate the fight of the year. Joe Lauzon and Jamie Varner turned a prelim into a bloodbath, and Jones, Silva, and Aldo all kept their belts while the sport waited for someone, anyone, to solve them.',
  2013: 'A genuinely great year. Jon Jones nearly lost everything to Alexander Gustafsson in a five-round classic, Mark Hunt and Bigfoot Silva slugged to the rare draw that nobody complained about, Diego Sanchez\'s face survived Gilbert Melendez, and Chris Weidman ended the longest title reign in UFC history by knocking out Anderson Silva, then beat him again in the rematch before the year was out.',
  2014: 'Matt Brown and Erick Silva beat the humanity out of each other in Cincinnati, Jose Aldo and Chad Mendes went five rounds at a pace featherweights were not supposed to survive, and TJ Dillashaw pulled one of the biggest upsets ever by dismantling Renan Barao. Meanwhile Robbie Lawler and Johny Hendricks split two wars over the welterweight belt.',
  2015: 'Lawler vs MacDonald 2 might be the greatest title fight ever, a fight that ended with both men broken and fans rate the best of the year by a distance. The same year gave us Cormier vs Gustafsson, Holly Holm head-kicking the Ronda Rousey era to a close, and Conor McGregor needing 13 seconds to take Jose Aldo\'s belt.',
  2016: 'Cub Swanson and Doo Ho Choi turned three rounds into an all-time classic that leads the year\'s fan ratings. Lawler vs Condit was a title fight decided by a single round of madness, Tony Ferguson welcomed Lando Vannata in chaos, and outside the cage 2016 was peak McGregor: two Diaz wars and two belts.',
  2017: 'The year Justin Gaethje arrived. His UFC debut against Michael Johnson tops the fan ratings, his war with Eddie Alvarez was somehow just as violent, and Garbrandt vs Dillashaw settled a grudge with a knockout. Add Demetrious Johnson\'s suplex-to-armbar, the single slickest finish in UFC history, and 2017 earns its reputation.',
  2018: 'Whittaker vs Romero 2 was ten rounds of the two toughest middleweights alive across two fights, and fans rate the rematch the best of the year. Poirier and Gaethje set the FOTY bar in April, Khabib vs McGregor broke the pay-per-view record and then broke the cage, and Daniel Cormier became a two-division champ.',
  2019: 'Israel Adesanya and Kelvin Gastelum went five rounds for the interim middleweight belt in an instant classic, and Holloway vs Poirier 2 paid off years of shared history. Jorge Masvidal produced the five-second flying knee, Nate Diaz came back after three years, and Stipe Miocic avenged himself on Daniel Cormier.',
  2020: 'The empty-arena year, and somehow one of the best fight years ever: with no crowds, the Apex became a laboratory for violence. Emmett vs Burgos and Figueiredo vs Moreno top the fan scores, Poirier vs Hooker was a war neither man fully recovered from that year, and Luque vs Price delivered exactly what it promised.',
  2021: 'Gaethje vs Chandler at UFC 268 was three rounds of the most concentrated chaos the lightweight division has ever produced, and fans score it the fight of the year. Oliveira climbed off the canvas to finish Chandler for the vacant belt, Holloway out-boxed Kattar while talking to the commentary desk mid-round, and McGregor\'s leg snapped against Poirier.',
  2022: 'Teixeira vs Prochazka is the highest fan-rated fight of the decade on this site, a title fight where the lead changed hands every round until a last-minute submission. Burns vs Chimaev answered whether the hype train could eat three rounds of hell, and Schnell vs Mudaerji stole a card in one round.',
  2023: 'The year belonged to the big stories, Jon Jones finally moving to heavyweight and Islam Makhachev vs Alexander Volkanovski twice, but the fan ratings tell you where the pure violence lived: Turner vs Hooker swinging for the fences, and unheralded wars like Algeo vs Brown proving the best fight on any card can come from anywhere.',
  2024: 'Max Holloway knocked out Justin Gaethje with one second left in the BMF fight, the most replayed buzzer-beater in the sport\'s history, and it sits near the top of the year\'s ratings alongside Rebecki vs Orolbai, a war most casual fans never saw. Alex Pereira spent the year headlining on short notice and knocking everyone out.',
  2025: 'Prochazka vs Rountree was exactly the kind of madness Prochazka fights seem contractually obligated to produce, and it leads the year\'s fan scores. Lopes vs Silva and Royval vs Van kept the lighter divisions violent, Ilia Topuria moved up and took a second belt, and Khamzat Chimaev finally got his title.',
  2026: 'The year is still being written, but Topuria vs Gaethje already looks like the fight to beat at a 9.7 fan rating. Curtis Blaydes and Josh Hokit turned a heavyweight scrap into an instant classic, and the McGregor comeback at UFC 329 became the most hyped and worst-rated main event we have ever tracked, 69 seconds and one blown knee.',
};
