services:
  # PostgreSQL Database
  - type: pserv
    name: fightcrewapp-db
    plan: free
    region: oregon
    databaseName: fightcrewapp
    databaseUser: fightcrewapp_user
    ipAllowList: []

  # Backend Web Service
  - type: web
    name: fightcrewapp-backend
    runtime: node
    plan: free
    region: oregon
    branch: main
    buildCommand: cd packages/backend && pnpm install && pnpm run db:generate && pnpm run build
    startCommand: cd packages/backend && pnpm run db:migrate:deploy && pnpm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: fightcrewapp-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: SKIP_EMAIL_VERIFICATION
        value: true
      - key: CORS_ORIGINS
        value: https://fightcrewapp.com,exp://expo.dev
