-- Add boxing weight classes to WeightClass enum

-- Men's boxing divisions
ALTER TYPE "WeightClass" ADD VALUE 'BOXING_MINIMUMWEIGHT';
ALTER TYPE "WeightClass" ADD VALUE 'BOXING_LIGHT_FLYWEIGHT';
ALTER TYPE "WeightClass" ADD VALUE 'BOXING_FLYWEIGHT';
ALTER TYPE "WeightClass" ADD VALUE 'BOXING_SUPER_FLYWEIGHT';
ALTER TYPE "WeightClass" ADD VALUE 'BOXING_BANTAMWEIGHT';
ALTER TYPE "WeightClass" ADD VALUE 'BOXING_SUPER_BANTAMWEIGHT';
ALTER TYPE "WeightClass" ADD VALUE 'BOXING_FEATHERWEIGHT';
ALTER TYPE "WeightClass" ADD VALUE 'BOXING_SUPER_FEATHERWEIGHT';
ALTER TYPE "WeightClass" ADD VALUE 'BOXING_LIGHTWEIGHT';
ALTER TYPE "WeightClass" ADD VALUE 'BOXING_SUPER_LIGHTWEIGHT';
ALTER TYPE "WeightClass" ADD VALUE 'BOXING_WELTERWEIGHT';
ALTER TYPE "WeightClass" ADD VALUE 'BOXING_SUPER_WELTERWEIGHT';
ALTER TYPE "WeightClass" ADD VALUE 'BOXING_MIDDLEWEIGHT';
ALTER TYPE "WeightClass" ADD VALUE 'BOXING_SUPER_MIDDLEWEIGHT';
ALTER TYPE "WeightClass" ADD VALUE 'BOXING_LIGHT_HEAVYWEIGHT';
ALTER TYPE "WeightClass" ADD VALUE 'BOXING_CRUISERWEIGHT';
ALTER TYPE "WeightClass" ADD VALUE 'BOXING_HEAVYWEIGHT';

-- Women's boxing divisions
ALTER TYPE "WeightClass" ADD VALUE 'BOXING_WOMENS_MINIMUMWEIGHT';
ALTER TYPE "WeightClass" ADD VALUE 'BOXING_WOMENS_LIGHT_FLYWEIGHT';
ALTER TYPE "WeightClass" ADD VALUE 'BOXING_WOMENS_FLYWEIGHT';
ALTER TYPE "WeightClass" ADD VALUE 'BOXING_WOMENS_SUPER_FLYWEIGHT';
ALTER TYPE "WeightClass" ADD VALUE 'BOXING_WOMENS_BANTAMWEIGHT';
ALTER TYPE "WeightClass" ADD VALUE 'BOXING_WOMENS_SUPER_BANTAMWEIGHT';
ALTER TYPE "WeightClass" ADD VALUE 'BOXING_WOMENS_FEATHERWEIGHT';
ALTER TYPE "WeightClass" ADD VALUE 'BOXING_WOMENS_SUPER_FEATHERWEIGHT';
ALTER TYPE "WeightClass" ADD VALUE 'BOXING_WOMENS_LIGHTWEIGHT';
ALTER TYPE "WeightClass" ADD VALUE 'BOXING_WOMENS_SUPER_LIGHTWEIGHT';
ALTER TYPE "WeightClass" ADD VALUE 'BOXING_WOMENS_WELTERWEIGHT';
ALTER TYPE "WeightClass" ADD VALUE 'BOXING_WOMENS_SUPER_WELTERWEIGHT';
ALTER TYPE "WeightClass" ADD VALUE 'BOXING_WOMENS_MIDDLEWEIGHT';
ALTER TYPE "WeightClass" ADD VALUE 'BOXING_WOMENS_SUPER_MIDDLEWEIGHT';
ALTER TYPE "WeightClass" ADD VALUE 'BOXING_WOMENS_LIGHT_HEAVYWEIGHT';
ALTER TYPE "WeightClass" ADD VALUE 'BOXING_WOMENS_CRUISERWEIGHT';
ALTER TYPE "WeightClass" ADD VALUE 'BOXING_WOMENS_HEAVYWEIGHT';
